name: UHF Server Dist (Wrapper)
slug: uhf_server_dist
description: Home Assistant add-on wrapper for uhf-server-dist.
url: https://github.com/fbradyirl/uhf-server-dist-ha-addon
version: "0.3.0"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
ingress: false
host_network: false
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: UHF Server HTTP API
webui: http://[HOST]:[PORT:8000]/
map:
  - data:rw
options:
  command: ""
  host: "0.0.0.0"
  port: 8000
  password: ""
  enable_commercial_detection: true
  extra_args: ""
  ffmpeg_path: ""
  comskip_path: ""
  db_path: ""
  log_level: "INFO"
schema:
  command: "str?"
  host: "str?"
  port: "int(1,65535)?"
  password: "str?"
  enable_commercial_detection: "bool?"
  extra_args: "str?"
  ffmpeg_path: "str?"
  comskip_path: "str?"
  db_path: "str?"
  log_level: "str?"